# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

COPY . .
RUN npm run build

ENTRYPOINT ["node", "dist/server.js"]
